language: node_js
node_js:
  - "8"
  - "10"
  - lts/*
  - node
script:
  - npm test
jobs:
  include:
    - stage: coverage
      node_js: lts/*
      script: npm run build:protos && npm run build:types && jest --coverage --coverageReporters=text-lcov | coveralls
